### ISSUE TITLE
No module named 'commands'

### ISSUE THREAD

**Issue by AMOz1** [dschil138/chatterstack#1]
I'm trying to run import chatterstack on google collab and I'm getting ModuleNotFoundError: No module named 'commands'
I googled it and it says **command** was deprecated since python version 2.6 and to use the **subprocess** module instead.

**Comment by dschil138** [comment]
the commands import should refer to the commands.py file within Chatterstack. I don't ever really use collab so I'm not super familiar with it, but if you have added chatterstack.py manually, you will have to also manually add the commands.py file as well. If you added it with pip I would think it should work? lmk if that helps

**Comment by dschil138** [comment]
Might be worth renaming commands.py to avoid confusion tho

**Comment by AMOz1** [comment]
don't take my hiccups as indication that something is wrong.. I have no idea what I'm doing. I'm just copy-pasting things around to see what sticks. I tried to install the chatterstack package in Replit editor and I got the same message ModuleNotFoundError: No module named 'commands'. I don't know how to install commands.py manually. But, please waste no time on this... as I can't even write any code. I'm just trying to make something going by copy-pasting things around :) 

What got me interested in this project was your comment on Reddit where you mentioned  " ...moving the "system" message around dynamically". I was exploring the possibility to assemble the system message dynamically on my own..as I noticed that whatever context is in the "system" has great impact on model's ability to reason.

**Comment by dschil138** [comment]
Oh yeah for sure, the system message thing was honestly my main motivation for starting to write the library at all.

So this was an actual bug! I tried to use chatterstack in colab and had the same issue. Turns I was trying to import `commands` from the wrong namespace. It should be fixed now if you want to try it again! (you will have to redo the `pip install chatterstack` step to get the updated version)

**Comment by dschil138** [comment]
Hey @AMOz1 I'm gonna close this as completed but if you try it and it doesn't work out lmk! I think it should be resolved tho
